import company_logo from '../../img/company_logo.png'
export const endpoint = "http://localhost:3000/api";
export const data = [
  {
    company_name: 'Microsoft',
    location: 'Delhi',
    work_mode: 'in-office',
    job_offer: '80k-120k',
    company_size: '100,000+ Employees',
    logo: company_logo,
    start_date: '10/06/2024',
    experience: '2-5 Years',
    last_date: '05/03/2024',
    probation_period: '3 months',
    skills: ['React', 'Node.js', 'Azure', 'Git', 'SQL'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Google',
    location: 'Gurgaon',
    work_mode: 'hybrid',
    job_offer: '90k-130k',
    company_size: '150,000+ Employees',
    logo: company_logo,
    start_date: '02/02/2024',
    experience: '3-6 Years',
    last_date: '10/03/2024',
    probation_period: '4 months',
    skills: ['Angular', 'Python', 'Google Cloud', 'Git', 'Machine Learning'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Amazon',
    location: 'Noida',
    work_mode: 'remote',
    job_offer: '100k-150k',
    company_size: '500,000+ Employees',
    logo: company_logo,
    start_date: '05/02/2024',
    experience: '4-8 Years',
    last_date: '15/03/2024',
    probation_period: '2 months',
    skills: ['React', 'Java', 'AWS', 'Git', 'DynamoDB'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Facebook',
    location: 'Hyderabad',
    work_mode: 'in-office',
    job_offer: '120k-180k',
    company_size: '75,000+ Employees',
    logo: company_logo,
    start_date: '01/03/2024',
    experience: '5-10 Years',
    last_date: '20/03/2024',
    probation_period: '3 months',
    skills: ['React', 'PHP', 'Hack', 'Git', 'MySQL'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Apple',
    location: 'Bangalore',
    work_mode: 'hybrid',
    job_offer: '110k-160k',
    company_size: '150,000+ Employees',
    logo: company_logo,
    start_date: '05/03/2024',
    experience: '3-7 Years',
    last_date: '25/03/2024',
    probation_period: '2 months',
    skills: ['Swift', 'Objective-C', 'iOS', 'Git', 'Xcode'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Tesla',
    location: 'Kolkata',
    work_mode: 'in-office',
    job_offer: '150k-200k',
    company_size: '50,000+ Employees',
    logo: company_logo,
    start_date: '10/03/2024',
    experience: '8-12 Years',
    last_date: '30/03/2024',
    probation_period: '3 months',
    skills: ['JavaScript', 'Python', 'C++', 'Git', 'Autopilot'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Netflix',
    location: 'Delhi',
    work_mode: 'remote',
    job_offer: '130k-180k',
    company_size: '10,000+ Employees',
    logo: company_logo,
    start_date: '09/03/2024',
    experience: '5-9 Years',
    last_date: '05/04/2024',
    probation_period: '2 months',
    skills: ['React', 'Java', 'Spring', 'Git', 'Microservices'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'LinkedIn',
    location: 'Gurgaon',
    work_mode: 'hybrid',
    job_offer: '110k-150k',
    company_size: '15,000+ Employees',
    logo: company_logo,
    start_date: '10/03/2024',
    experience: '4-8 Years',
    last_date: '10/04/2024',
    probation_period: '3 months',
    skills: ['React', 'Node.js', 'Express.js', 'Git', 'MongoDB'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Uber',
    location: 'Noida',
    work_mode: 'in-office',
    job_offer: '120k-170k',
    company_size: '20,000+ Employees',
    logo: company_logo,
    start_date: '08/03/2024',
    experience: '6-10 Years',
    last_date: '15/04/2024',
    probation_period: '2 months',
    skills: ['React', 'Node.js', 'Python', 'Git', 'RESTful APIs'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Twitter',
    location: 'Delhi',
    work_mode: 'remote',
    job_offer: '100k-140k',
    company_size: '5,000+ Employees',
    logo: company_logo,
    start_date: '01/04/2024',
    experience: '3-7 Years',
    last_date: '20/04/2024',
    probation_period: '3 months',
    skills: ['React', 'Java', 'Spring Boot', 'Git', 'Kafka'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Salesforce',
    location: 'Gurgaon',
    work_mode: 'hybrid',
    job_offer: '130k-180k',
    company_size: '50,000+ Employees',
    logo: company_logo,
    start_date: '05/04/2024',
    experience: '5-9 Years',
    last_date: '25/04/2024',
    probation_period: '2 months',
    skills: ['React', 'Apex', 'Salesforce Lightning', 'Git', 'SQL'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Adobe',
    location: 'Noida',
    work_mode: 'in-office',
    job_offer: '110k-160k',
    company_size: '20,000+ Employees',
    logo: company_logo,
    start_date: '10/04/2024',
    experience: '4-8 Years',
    last_date: '30/04/2024',
    probation_period: '3 months',
    skills: ['React', 'Node.js', 'JavaScript', 'Git', 'Photoshop'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Intel',
    location: 'Hyderabad',
    work_mode: 'remote',
    job_offer: '120k-170k',
    company_size: '50,000+ Employees',
    logo: company_logo,
    start_date: '05/04/2024',
    experience: '6-10 Years',
    last_date: '05/05/2024',
    probation_period: '2 months',
    skills: ['C++', 'Java', 'Python', 'Git', 'Machine Learning'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'IBM',
    location: 'Bangalore',
    work_mode: 'in-office',
    job_offer: '130k-180k',
    company_size: '300,000+ Employees',
    logo: company_logo,
    start_date: '02/04/2024',
    experience: '5-9 Years',
    last_date: '10/05/2024',
    probation_period: '3 months',
    skills: ['Java', 'Python', 'IBM Cloud', 'Git', 'SQL'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Cisco',
    location: 'Kolkata',
    work_mode: 'hybrid',
    job_offer: '110k-150k',
    company_size: '70,000+ Employees',
    logo: company_logo,
    start_date: '25/04/2024',
    experience: '4-8 Years',
    last_date: '15/05/2024',
    probation_period: '2 months',
    skills: ['Networking', 'Python', 'Cisco IOS', 'Git', 'CCNA'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'HP',
    location: 'Delhi',
    work_mode: 'remote',
    job_offer: '120k-170k',
    company_size: '50,000+ Employees',
    logo: company_logo,
    start_date: '01/05/2024',
    experience: '6-10 Years',
    last_date: '20/05/2024',
    probation_period: '3 months',
    skills: ['Java', 'C#', '.NET', 'Git', 'Printer Drivers'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Oracle',
    location: 'Gurgaon',
    work_mode: 'in-office',
    job_offer: '140k-200k',
    company_size: '100,000+ Employees',
    logo: company_logo,
    start_date: '05/05/2024',
    experience: '8-12 Years',
    last_date: '25/05/2024',
    probation_period: '2 months',
    skills: ['Java', 'PL/SQL', 'Oracle Database', 'Git', 'SQL'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Dell',
    location: 'Noida',
    work_mode: 'hybrid',
    job_offer: '130k-180k',
    company_size: '150,000+ Employees',
    logo: company_logo,
    start_date: '10/05/2024',
    experience: '5-9 Years',
    last_date: '30/05/2024',
    probation_period: '3 months',
    skills: ['C#', 'JavaScript', '.NET', 'Git', 'Dell EMC'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'NVIDIA',
    location: 'Hyderabad',
    work_mode: 'remote',
    job_offer: '150k-220k',
    company_size: '20,000+ Employees',
    logo: company_logo,
    start_date: '15/05/2024',
    experience: '8-12 Years',
    last_date: '05/06/2024',
    probation_period: '2 months',
    skills: ['C++', 'CUDA', 'Machine Learning', 'Git', 'Graphics Programming'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'VMware',
    location: 'Kolkata',
    work_mode: 'in-office',
    job_offer: '140k-190k',
    company_size: '30,000+ Employees',
    logo: company_logo,
    start_date: '20/05/2024',
    experience: '6-10 Years',
    last_date: '10/06/2024',
    probation_period: '3 months',
    skills: ['Java', 'Python', 'VMware vSphere', 'Git', 'Virtualization'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Accenture',
    location: 'Delhi',
    work_mode: 'hybrid',
    job_offer: '120k-170k',
    company_size: '500,000+ Employees',
    logo: company_logo,
    start_date: '25/05/2024',
    experience: '5-9 Years',
    last_date: '15/06/2024',
    probation_period: '2 months',
    skills: ['Java', 'Spring Boot', 'Microservices', 'Git', 'DevOps'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'SAP',
    location: 'Gurgaon',
    work_mode: 'remote',
    job_offer: '130k-180k',
    company_size: '100,000+ Employees',
    logo: company_logo,
    start_date: '01/06/2024',
    experience: '6-10 Years',
    last_date: '20/06/2024',
    probation_period: '3 months',
    skills: ['ABAP', 'SAP HANA', 'UI5', 'Git', 'ERP'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  },
  {
    company_name: 'Capgemini',
    location: 'Noida',
    work_mode: 'in-office',
    job_offer: '110k-150k',
    company_size: '200,000+ Employees',
    logo: company_logo,
    start_date: '05/06/2024',
    experience: '4-8 Years',
    last_date: '25/06/2024',
    probation_period: '2 months',
    skills: ['Java', 'Spring', 'Hibernate', 'Git', 'Agile'],
    requirement: ['Design, code, debug, and unit test Android mobile applications',
      'Connecting with the product team to understand the features/business requirements for Android app development',
      'Integrate third-party services, such as REST APIs and Firebase',
      'Able to Work on Live Data and Good at Layout Design',
      'Conducting thorough testing and troubleshooting to ensure high-quality performance and bug-free applications',
      'Assisting in the documentation and version control of app development processes',
      'Experience with third-party libraries and APIs'
    ],
    perks_benefit: [
      'Opportunity to improve your system architecture and coding skills while working on real-world & challenging problem statements',
      'Work in a professional set-up where all team members operate remotely to deliver superior products at a record pace while choosing the work timing of their liking',
      'We have an interesting culture where team members share info',
      'An above-industry average stipend that is linked to the quality of the work you produce and the quality of your involvement and ownership of the problem statement',
      'We respect your suggestion & feedback to improve both technical & non technical end.'
    ],
    eligibility: [
      'Should have high-quality problem-solving skills with a fundamental understanding of Kotlin Coroutine, Jetpack Compose, Room database, Paging3, navigation compose, MVVM & gRPC',
      'Should have a bachelor degree in computer science',
      'Should have an ownership mentality where you are responsible for the end-to-end delivery of your task that is not just limited to executing your part but also collaborating with team members to ensure the timely delivery of the requirement',
      'At least 2 years of professional experience in Mobile App Development or related field',
      'Strong knowledge of Java or Kotlin for Android application development',
      'Good understanding of MVC architecture design pattern',
      'Hands-on experience with SQL database management system'
    ],
    joining_date: 'Immediate'
  }
];

export const noteForHR = 'Dear Hiring Manager,\n\nI am writing to express my keen interest in the developer role at your esteemed company. With a strong background in [mention relevant skills or technologies], I am confident in my ability to contribute effectively to your team.\n\nThroughout my career, I have successfully [mention specific achievements or projects] that demonstrate my problem-solving skills, attention to detail, and passion for creating high-quality software solutions. My expertise in [mention specific technologies, languages, or frameworks] aligns well with the requirements of the position, and I am eager to bring my skills to your dynamic team.\n\nI am particularly drawn to your company commitment to [mention specific values or goals of the company], and I believe that my technical proficiency and collaborative approach make me a strong fit for the innovative work your team is doing.\n\nThank you for considering my application.I am excited about the opportunity to contribute to your company success, and I look forward to the possibility of discussing how my skills and experiences align with your team needs.\n\nSincerely, [Your Full Name]'